### ISSUE TITLE
Add options for last period

### ISSUE THREAD

**Issue by jghyllebert** [julzhk/opfistula_case_manager#27]
Date of Last Period - add an option for "menopause/amenorrhea" or "not menstruating" or "not applicable" - just so there's an option for the women whose last period was eons ago and we don't really need to know the date.  We ask for last period mostly so the surgeon can use it as a first-round data point to check if they're currently pregnant.  

*-- Jenny's mail of 28/12*

**Comment by julzhk** [comment]
NB: on 'status' form
